# Generated by Django 4.0.1 on 2022-02-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapists',
            name='id_document_n',
            field=models.IntegerField(unique=True),
        ),
    ]
