# Generated by Django 4.0.1 on 2022-02-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='id_document_n',
            field=models.IntegerField(unique=True),
        ),
    ]
