# Generated by Django 4.0.1 on 2022-02-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rooms_shifts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='day_end',
            field=models.DateField(null=True),
        ),
    ]
