# Generated by Django 4.0.2 on 2022-03-11 01:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0006_alter_patients_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='owner',
        ),
        migrations.AddField(
            model_name='patients',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=models.SET('DELETED'), related_name='created_by_patient', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('DELETED'), related_name='updated_by_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
