# Generated by Django 4.0.2 on 2022-03-11 02:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0007_remove_patients_owner_patients_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=models.SET('DELETED'), related_name='created_by_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patients',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=models.SET('DELETED'), related_name='updated_by_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
