# Generated by Django 4.0.1 on 2022-02-09 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapists', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rental', models.BooleanField()),
                ('is_session', models.BooleanField()),
                ('date', models.DateField()),
                ('operation_type', models.IntegerField(choices=[(1, 'Rental'), (2, 'Sessions')])),
                ('units', models.SmallIntegerField()),
                ('unit_price', models.FloatField()),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document_cust', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_identificator', models.IntegerField()),
                ('identificator', models.IntegerField()),
                ('is_company', models.BooleanField()),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='accounting.providers')),
            ],
        ),
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.IntegerField(choices=[(1, 'Morning'), (2, 'Afternoon')])),
                ('period_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='client_rental', to='accounting.clients')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_company', models.BooleanField()),
                ('company_id', models.IntegerField(null=True)),
                ('to_therapist', models.BooleanField()),
                ('units', models.SmallIntegerField()),
                ('unit_price', models.FloatField()),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=models.SET('DELETED'), to='accounting.providerservices')),
                ('provider', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='provider_purchase', to='accounting.providers')),
                ('therapist_id', models.ForeignKey(null=True, on_delete=models.SET('DELETED'), to='therapists.therapists')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbu', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile_1', models.PositiveBigIntegerField()),
                ('mobile_2', models.PositiveBigIntegerField(null=True)),
                ('zip_code', models.SmallIntegerField()),
                ('address_street', models.CharField(max_length=200)),
                ('address_num', models.IntegerField()),
                ('address_floor', models.CharField(max_length=10, null=True)),
                ('address_ap', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_details', to='accounting.providers')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyOutReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_purchase', models.BooleanField()),
                ('is_fee', models.BooleanField()),
                ('reference', models.TextField(max_length=500)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(null=True, on_delete=models.SET('DELETED'), related_name='purchase_moneyout', to='accounting.purchaseinvoices')),
                ('therapist', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='therapist_moneyout', to='therapists.therapists')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyInReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='bill_moneyin', to='accounting.bills')),
            ],
        ),
        migrations.CreateModel(
            name='CreditNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='bill_creditnote', to='accounting.bills')),
            ],
        ),
        migrations.AddField(
            model_name='bills',
            name='client',
            field=models.ForeignKey(db_column='id_document_cust', on_delete=models.SET('DELETED'), to='accounting.clients'),
        ),
        migrations.AddField(
            model_name='bills',
            name='pmt_method',
            field=models.ForeignKey(on_delete=models.SET('DELETED'), to='accounting.paymentmethods'),
        ),
        migrations.AddField(
            model_name='bills',
            name='rental',
            field=models.ForeignKey(null=True, on_delete=models.SET('DELETED'), related_name='rental_bill', to='accounting.rentals'),
        ),
        migrations.AddField(
            model_name='bills',
            name='session',
            field=models.ForeignKey(null=True, on_delete=models.SET('DELETED'), related_name='session_bill', to='patients.patientsessions'),
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='purchase_asset', to='accounting.purchaseinvoices')),
            ],
        ),
    ]
