# Generated by Django 4.0.1 on 2022-02-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0002_alter_therapists_id_document_n'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document_cust', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('position', models.IntegerField(choices=[(1, 'Therapist'), (2, 'Capitalist')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='moneyinreceipts',
            name='is_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moneyinreceipts',
            name='is_capital_contribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moneyoutreceipts',
            name='is_withdrawal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moneyinreceipts',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=models.SET('DELETED'), related_name='bill_moneyin', to='accounting.bills'),
        ),
        migrations.AlterField(
            model_name='moneyoutreceipts',
            name='is_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moneyoutreceipts',
            name='is_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moneyoutreceipts',
            name='therapist',
            field=models.ForeignKey(null=True, on_delete=models.SET('DELETED'), related_name='therapist_moneyout', to='therapists.therapists'),
        ),
        migrations.CreateModel(
            name='CapitalWithdrawals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='partner_withdrawals', to='accounting.partners')),
            ],
        ),
        migrations.CreateModel(
            name='CapitalContributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='partner_contributions', to='accounting.partners')),
            ],
        ),
        migrations.AddField(
            model_name='moneyinreceipts',
            name='contribution',
            field=models.ForeignKey(null=True, on_delete=models.SET('DELETED'), related_name='contribution_moneyin', to='accounting.capitalcontributions'),
        ),
        migrations.AddField(
            model_name='moneyoutreceipts',
            name='witdrawal',
            field=models.ForeignKey(default=0, on_delete=models.SET('DELETED'), related_name='withdrawal_moneyout', to='accounting.capitalwithdrawals'),
            preserve_default=False,
        ),
    ]
