# Generated by Django 4.0.1 on 2022-02-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_partners_moneyinreceipts_is_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='is_rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bills',
            name='is_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='providers',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='to_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='to_therapist',
            field=models.BooleanField(default=False),
        ),
    ]
